version: "3.9"
services:
  mern:
    build: .
    ports:
      - "4000:4000"
    links:
      - helloMySQL
  helloMySQL:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=taskDB